version: 1
accounts:
- name: alice
  coins:
  - 20000token
  - 200000000stake
- name: bob
  coins:
  - 10000token
  - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
validators:
- name: alice
  bonded: 100000000stake

genesis:
  genesis_time: "2024-03-26T08:00:00.000000Z"
  consensus:
    params:
      abci:
        vote_extensions_enable_height: "1"
  app_state:
    phoenix:
      params:
        proxy: proxy
        shardId: "1"
        vdf: 1000
      virtualBlockCount: 2
      virtualBlockList:
      - id: 0
      - id: 1
        time: 1711440000
        parent: dV5iFmKiCIkCO24UJTBRSEFyrCELedW0Jk89M8hQWVs=


